behaviors:
  SnowballTarget:
    trainer_type: ppo
    summary_freq: 10000
    keep_checkpoints: 10
    checkpoint_interval: 50000
    max_steps: 200000
    time_horizon: 64
    threaded: true
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: linear
      batch_size: 128
      buffer_size: 4048
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.97
        strength: 1.0